version: "3.8"

services:
  django:
    build: .
    container_name: django
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
  pgdb:
    image: postgres:12.3
    container_name: pgdb
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: practice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jv06kgus
    volumes:
      - ./db:/var/lib/postgresql/data/
