version: "3.8"
services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - dbv2
  dbv2:
    image: postgres
    container_name: dbv2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jv06kgus
      POSTGRES_DB: practice_db
