version: "3.8"

services:
  django:
    build: .
    container_name: django
    restart: always
    command: python manage.py runserver 0.0.0.0:1337
    volumes:
      - .:/usr/src/app
    ports:
      - "1337:1337"
    depends_on:
      - pgdb

  pgdb:
    image: postgres:12.3
    container_name: pgdb
    restart: always
    ports:
      - 5433:5432

    environment:
      POSTGRES_DB: practice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jv06kgus
    volumes:
      - ./db:/var/lib/postgresql/data/

  kong-database:
    image: postgres:9.6
    container_name: kong-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong

    volumes:
      - "db-data-kong-postgres:/var/lib/postgresql/data"

  kong-migrations:
    image: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations bootstrap
    restart: on-failure

    depends_on:
      - kong-database

  kong:
    image: kong
    container_name: kong

    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: on-failure
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    links:
      - kong-database:kong-database

    depends_on:
      - kong-migrations

  konga:
    image: pantsel/konga

    links:
      - "kong:kong"
    container_name: konga

    environment:
      # TOKEN_SECRET: ${KONGA_TOKEN_SECRET}
      # DB_ADAPTER: ${KONG_DATABASE}
      # NODE_ENV: ${KONGA_ENV}
      # KONGA_HOOK_TIMEOUT: 10000
      - NODE_ENV=production
    restart: on-failure
    ports:
      - $KONGA_PORT:1337
    depends_on:
      - kong-database

volumes:
  db-data-kong-postgres:
