# Generated by Django 3.2 on 2021-04-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
