# Generated by Django 3.2.2 on 2021-05-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='parent_id',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
