# Generated by Django 3.2 on 2021-05-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_bookablegroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookableGroup',
        ),
    ]
