# Generated by Django 3.2 on 2021-05-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0006_alter_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BookableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookable_type', models.PositiveSmallIntegerField(choices=[(1, 'Workspace'), (2, 'Meeting room'), (3, 'Parking spot')])),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BookableTypeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_limit', models.PositiveSmallIntegerField()),
                ('meeting_room_limit', models.PositiveSmallIntegerField()),
                ('parking_spot_limit', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('bookable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookable')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.participation')),
            ],
        ),
        migrations.AddField(
            model_name='bookable',
            name='bookable_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookabletype'),
        ),
        migrations.AddField(
            model_name='bookable',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
