# Generated by Django 3.2.2 on 2021-05-12 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_venue'),
        ('booking', '0002_bookable_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookable',
            name='venue_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='team.venue'),
            preserve_default=False,
        ),
    ]
