# Generated by Django 3.2.2 on 2021-05-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_venue'),
        ('booking', '0003_bookable_venue_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookable')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.venue')),
            ],
        ),
    ]
