# Generated by Django 3.2 on 2021-04-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookabletype_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookabletype',
            old_name='limit',
            new_name='meeting_room_limit',
        ),
    ]
