# Generated by Django 3.2.2 on 2021-05-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_teamvenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamvenue',
            name='bookable_id',
        ),
        migrations.AddField(
            model_name='teamvenue',
            name='bookable_id',
            field=models.ManyToManyField(blank=True, to='booking.Bookable'),
        ),
        migrations.RemoveField(
            model_name='teamvenue',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='teamvenue',
            name='booking_id',
            field=models.ManyToManyField(blank=True, to='booking.Booking'),
        ),
    ]
