# Generated by Django 3.2 on 2021-04-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_limit_bookabletype_meeting_room_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookabletype',
            name='meeting_room_limit',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
