# Generated by Django 3.2 on 2021-04-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_bookabletype_meeting_room_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookableTypeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_limit', models.PositiveSmallIntegerField()),
                ('meeting_room_limit', models.PositiveSmallIntegerField()),
                ('parking_spot_limit', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
