# Generated by Django 3.2 on 2021-04-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bookabletypelimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookabletype',
            name='meeting_room_limit',
        ),
    ]
