# Generated by Django 3.2 on 2021-04-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bookable_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookable',
            old_name='group_id',
            new_name='group',
        ),
    ]
