# Generated by Django 3.2 on 2021-04-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('booking', '0009_rename_group_id_bookable_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookable',
            name='group',
            field=models.ManyToManyField(null=True, to='group.Group'),
        ),
    ]
