# Generated by Django 3.2 on 2021-04-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_bookable_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookable',
            old_name='group',
            new_name='group_id',
        ),
    ]
