# Generated by Django 3.2 on 2021-04-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('booking', '0012_rename_group_bookable_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookable',
            name='group_id',
            field=models.ManyToManyField(blank=True, to='group.Group'),
        ),
    ]
